spring:
  application:
    name: jup-jup

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jupjup?serverTimezone=Asia/Seoul
    username: 
    password: 



  jpa:
    hibernate:
      ddl-auto: update  # 필요에 따라 create, create-drop, validate 등으로 변경 가능
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect // 이거 왜 사용이 안되냐
    show-sql: true  # 콘솔에 SQL 쿼리 출력 (개발 중에만 사용 권장)
    generate-ddl: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-name: google
            client-id: 
            client-secret: 
            redirect-uri: https://jupjup.store/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile,email

          naver:
            client-name: naver
            client-id: 
            client-secret: 
            redirect-uri: https://jupjup.store/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
          kakao:
            client-id: 
            scope: profile_nickname
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: https://jupjup.store/login/oauth2/code/kakao


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


springdoc:
  swagger-ui:
    url: '/docs/api.yaml'

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-response: true

#logging:
#  level:
#    root: DEBUG
#    org.springframework.security: DEBUG
