name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 */5 * *'  # 5일마다 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            back-end-app:latest
            back-end-app:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo su -c "cd /root/Back-end && docker-compose pull && docker-compose --env-file .env up -d"
            
            # 헬스 체크
            MAX_RETRIES=5
            RETRY_INTERVAL=10
            for i in $(seq 1 $MAX_RETRIES); do
              if curl -f http://localhost:8080/health; then 
                echo 'Application is healthy'
                exit 0
              fi
              echo "Health check failed. Retrying in $RETRY_INTERVAL seconds..."
              sleep $RETRY_INTERVAL
            done
            
            # 롤백
            echo "Health check failed after $MAX_RETRIES attempts. Rolling back..."
            sudo su -c "docker-compose down && docker-compose pull back-end-app:$(docker inspect --format='{{index .Config.Labels \"org.opencontainers.image.revision\"}}' back-end-app:latest) && docker-compose --env-file .env up -d"
            exit 1

  cleanup:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Clean up old Docker images, containers, and volumes
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu  # 'ubuntu' 사용자로 로그인
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker container prune -f
            sudo docker volume prune -f
            sudo docker image prune -af --filter "until=120h"
            sudo docker network prune -f
            sudo docker system prune -af